server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /bej3

spring:
  datasource:
    url: "jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  
  sql:
    init:
      mode: never

  web:
    cors:
      allowed-origins: "${CORS_ALLOWED_ORIGINS}"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    stomp:
      port: ${RABBITMQ_STOMP_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}


firebase:
  config:
    service-account-key-path: classpath:datn-e3c62-firebase-adminsdk-fbsvc-8b853f1fc7.json
    project-id: ${}
    database-url: ${FIREBASE_DATABASE_URL}
    storage-bucket: ${FIREBASE_STORAGE_BUCKET}
      
jwt:
  signerKey: "${JWT_SIGNER_KEY}"

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}