server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /bej3

spring:
  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:new_bej_sp3}?createDatabaseIfNotExist=true"
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  
  sql:
    init:
      mode: never

  web:
    cors:
      allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:5173}"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:61613}
    stomp:
      port: ${RABBITMQ_STOMP_PORT:61613}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}


firebase:
  config:
    service-account-key-path: classpath:datn-e3c62-firebase-adminsdk-fbsvc-8b853f1fc7.json
    project-id: ${FIREBASE_PROJECT_ID:datn-e3c62}
    database-url: ${FIREBASE_DATABASE_URL:https://datn-e3c62-default-rtdb.asia-southeast1.firebasedatabase.app/}
    storage-bucket: ${FIREBASE_STORAGE_BUCKET:datn-e3c62.appspot.com}
      
jwt:
  signerKey: "${JWT_SIGNER_KEY:7bZydhCMPlM7eKuKjxy1gIhbtMo7hTPNvYJr2FguJZtvxpeQ21K3MjP90WjNtYLO}"