server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /bej3

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/new_bej_sp3?createDatabaseIfNotExist=true"
    username: root
    password: trucdang02
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  
  sql:
    init:
      mode: never

  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

  rabbitmq:
    host: localhost
    port: 61613
    username: guest
    password: guest


firebase:
  config:
    service-account-key-path: classpath:datn-e3c62-firebase-adminsdk-fbsvc-8b853f1fc7.json
    project-id: datn-e3c62
    database-url: https://datn-e3c62-default-rtdb.asia-southeast1.firebasedatabase.app/
    storage-bucket: datn-e3c62.appspot.com
      
jwt:
  signerKey: "7bZydhCMPlM7eKuKjxy1gIhbtMo7hTPNvYJr2FguJZtvxpeQ21K3MjP90WjNtYLO"